import Header from './Header';
import Footer from './Footer';
import Providers from './providers';
import Dialog from './Dialog';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
};

const RootLayout = ({ children }: Props) => {
  return (
    <html lang="zh-TW">
      <body>
        <Providers>
          <Dialog />
          <Header />
          <div style={{ minHeight: 'calc(100vh - 379px)' }}>{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
